package constants

const (
	ConversationDirect    = "direct"
	ConversationGroup     = "group"
	ConversationBroadcast = "broadcast"
	ConversationSelf      = "self"
	ConversationTemporary = "temporary"
	ConversationPrivate   = "private"

	MemberRoleOwner  = "owner"
	MemberRoleAdmin  = "admin"
	MemberRoleMember = "member"

	MessageText       = "text"
	MessageMarkdown   = "markdown"
	MessageEmoji      = "emoji"
	MessageGIF        = "gif"
	MessageSticker    = "sticker"
	MessageImage      = "image"
	MessageVideo      = "video"
	MessageAudio      = "audio"
	MessageVoice      = "voice"
	MessageDocument   = "document"
	MessagePDF        = "pdf"
	MessageZIP        = "zip"
	MessageRAR        = "rar"
	MessageAPK        = "apk"
	MessageLocation   = "location"
	MessageContact    = "contact"
	MessageCode       = "code"
	MessagePoll       = "poll"
	MessageCalendar   = "calendar"
	MessageTask       = "task"
	MessageLink       = "link"

	StatusSending   = "sending"
	StatusSent      = "sent"
	StatusDelivered = "delivered"
	StatusRead      = "read"
	StatusSeen      = "seen"
	StatusFailed    = "failed"

	PresenceOnline    = "online"
	PresenceOffline   = "offline"
	PresenceAway      = "away"
	PresenceBusy      = "busy"
	PresenceInvisible = "invisible"
	PresenceIdle      = "idle"

	WSEventMessage       = "message"
	WSEventMessageEdit   = "message.edit"
	WSEventMessageDelete = "message.delete"
	WSEventTyping        = "typing"
	WSEventRecording     = "recording"
	WSEventPresence      = "presence"
	WSEventReceipt       = "receipt"
	WSEventReaction      = "reaction"
	WSEventPin           = "pin"
	WSEventConversation  = "conversation"
	WSEventNotification  = "notification"
	WSEventCall          = "call"
	WSEventVoice         = "voice"
	WSEventPing          = "ping"
	WSEventPong          = "pong"
	WSEventJoin          = "join"
	WSEventLeave         = "leave"

	RedisChannelPrefix = "chat:events:"
	RedisPresenceKey   = "chat:presence:"
	RedisTypingKey     = "chat:typing:"
)
